# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Databricks.DatabricksCLI
PackageVersion: 0.274.0
PackageLocale: en-US
Publisher: Databricks
PublisherUrl: https://databricks.com/
PublisherSupportUrl: https://github.com/databricks/cli/issues
PackageName: DatabricksCLI
PackageUrl: https://github.com/databricks/cli
License: DB license
LicenseUrl: https://github.com/databricks/cli/blob/HEAD/LICENSE
ShortDescription: Databricks Command Line Interface
Tags:
- command-line-interface
- databricks
ReleaseNotes: |-
  Bundles
  - Fix a panic in TF when it fails to read the job (#3799)
  - For secret scopes, no longer remove current user's permissions (#3780)
  - Automatically add owner permissions during bundle initialization, this makes final permissions visible in 'bundle validate -o json' (#3780)
ReleaseNotesUrl: https://github.com/databricks/cli/releases/tag/v0.274.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
