# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: LutzRoeder.Netron
PackageVersion: 8.7.2
Platform:
- Windows.Desktop
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x86
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v8.7.2/Netron-Setup-8.7.2.exe
  InstallerSha256: A7730B7FC8A12C2B6C272ABF79648D50F3414DDB79384C2698F8B11604F1F7E4
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
- Architecture: arm64
  Scope: user
  InstallerType: nullsoft
  InstallerUrl: https://github.com/lutzroeder/netron/releases/download/v8.7.2/Netron-Setup-8.7.2.exe
  InstallerSha256: A7730B7FC8A12C2B6C272ABF79648D50F3414DDB79384C2698F8B11604F1F7E4
  InstallerLocale: en-US
  InstallerSwitches:
    Custom: /NORESTART
  UpgradeBehavior: install
FileExtensions:
- armnn
- caffemodel
- circle
- ckpt
- cmf
- dlc
- dnn
- gguf
- h5
- hd5
- hdf5
- hn
- kann
- keras
- kgraph
- kmodel
- lite
- mar
- maxviz
- meta
- mge
- mlir
- mlirbc
- mlmodel
- mlnet
- mlpackage
- mnn
- model
- nb
- ngf
- nn
- nnp
- npy
- npz
- om
- onnx
- ort
- paddle
- param
- pb
- pbtxt
- pdiparams
- pdmodel
- pdopt
- pdparams
- pickle
- pkl
- prototxt
- pt
- pt2
- pte
- pth
- ptl
- rknn
- safetensors
- t7
- tfl
- tflite
- tm
- tmfile
- tnnproto
- torchscript
- uff
- xmodel
ManifestType: installer
ManifestVersion: 1.6.0
