# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: hrzlgnm.mdns-browser
PackageVersion: 0.25.1
PackageLocale: en-US
Publisher: hrzlgnm
PublisherUrl: https://github.com/hrzlgnm
PublisherSupportUrl: https://github.com/hrzlgnm/mdns-browser/issues
PrivacyUrl: https://github.com/hrzlgnm/mdns-browser/blob/main/PRIVACY.md
Author: hrzlgnm
PackageName: mdns-browser
PackageUrl: https://github.com/hrzlgnm/mdns-browser
License: MIT
LicenseUrl: https://github.com/hrzlgnm/mdns-browser/blob/HEAD/LICENSE
Copyright: Copyright (c) 2024 hrzlgnm
ShortDescription: mDNS Browser
Description: mDNS Browser
Tags:
- leptos
- mdns-sd
- rust
- tauri
- thaw
ReleaseNotes: |-
  What's Changed
  🧰 Maintenance
  - #1473 chore(ci): Remove linting in publish workflow @hrzlgnm
  - #1474 chore(ci): winget: Fix url generation after artifact name change @hrzlgnm
  - #1475 chore(aur): Fixup artifact names in AUR update workflow @hrzlgnm
  - #1480 chore(ci): Update workflows from ubuntu-24.04 to use ubuntu-latest @hrzlgnm
  - #1481 chore(coderabbit): Disable docstring check @hrzlgnm
  - #1484 chore(ci): Add ubuntu builder docker image @hrzlgnm
  - #1487 chore(ubuntu-builder): Add missing dependencies @hrzlgnm
  - #1486 chore(ci): Use ubuntu builder docker image for lint steps @hrzlgnm
  - #1488 chore(ci): Also build docker images in PR on updates @hrzlgnm
  - #1489 chore(ci): Also use ubuntu builder in desktop build workflow @hrzlgnm
  - #1492 chore(renovate): Fix matching and replacing container_image in workflows @hrzlgnm
  - #1498 chore(ci): Run clippy with multiple targets @hrzlgnm
  - #1501 chore(ci): consolidate rust caches @hrzlgnm
  - #1502 chore(ocd): reorder matrix definitions and update job names @hrzlgnm
  - #1507 chore(ci): Add unzip to ubuntu builder dependencies @hrzlgnm
  :arrow_up: Dependency Updates
  - #1477 chore(deps): update ghcr.io/hrzlgnm/mdns-browser-void-package-builder:v1 docker digest to 893e7ef @renovate[bot]
  - #1478 chore(deps): update ghcr.io/hrzlgnm/mdns-browser-arch-aur-builder:v1 docker digest to ba36980 @renovate[bot]
  - #1479 chore(deps): update ghcr.io/hrzlgnm/mdns-browser-arch-aur-builder:v1 docker digest to a6886bd @renovate[bot]
  - #1482 chore(deps): update rust crate tauri-plugin-clipboard-manager to v2.3.1 @renovate[bot]
  - #1483 chore(deps): update rust crate tauri-plugin-opener to v2.5.1 @renovate[bot]
  - #1485 chore(deps): pin ubuntu docker tag to 66460d5 @renovate[bot]
  - #1493 chore(deps): lock file maintenance @renovate[bot]
  - #1495 chore(deps): update rust crate tauri-plugin-log to v2.7.1 @renovate[bot]
  - #1494 chore(deps): update rust crate tauri-plugin-clipboard-manager to v2.3.2 @renovate[bot]
  - #1496 chore(deps): update rust crate tauri-plugin-opener to v2.5.2 @renovate[bot]
  - #1499 chore(deps): update rust crate leptos to v0.8.12 @renovate[bot]
  - #1504 chore(deps): update tauri monorepo to v2.9.2 @renovate[bot]
  - #1503 chore(deps): update rust crate clap to v4.5.51 - autoclosed @renovate[bot]
  - #1505 chore(deps): update ghcr.io/hrzlgnm/mdns-browser-void-package-builder:v1 docker digest to 2dd8706 @renovate[bot]
  - #1506 fix(deps): update rust crate mdns-sd to 0.16 @renovate[bot]
  - #1508 chore(deps): update ghcr.io/hrzlgnm/mdns-browser-ubuntu-builder:v1 docker digest to 06bb8f7 @renovate[bot]
ReleaseNotesUrl: https://github.com/hrzlgnm/mdns-browser/releases/tag/mdns-browser-v0.25.1
ManifestType: defaultLocale
ManifestVersion: 1.9.0
