# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: CDESoftware.BLS-2026
PackageVersion: 38.01.0008
InstallerType: exe
InstallerSwitches:
  Silent: /exenoui /qn /norestart
Installers:
- Architecture: x86
  InstallerUrl: https://static.cdesoftware.com/bls2026/BLS2026INSTALLER.EXE
  InstallerSha256: f0f41b47544d6da603fd1ac5b5606d8148bbafdeb7df1e778921ad62592925da
ManifestType: installer
ManifestVersion: 1.9.0